import { useState, useEffect } from 'react'
import api from '@services/api'
import './Reports.css'

interface Report {
  id: string
  name: string
  date: string
  size: string
  type: string
  status: 'generated' | 'processing' | 'failed'
}

/* Download handler — CSV as Blob, PDF as printable HTML window */
function downloadReport(report: Report) {
  if (report.type === 'CSV') {
    // Real CSV blob download
    const rows = [
      ['Report Name', 'Date', 'Size', 'Type', 'Status'],
      [report.name, report.date, report.size, report.type, report.status],
    ]
    const csv = rows.map(r => r.map(c => `"${c}"`).join(',')).join('\n')
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `${report.name.replace(/[^a-z0-9]/gi, '_')}.csv`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } else {
    // Open a styled HTML print window — user saves as PDF via browser
    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${report.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #fff; color: #1a1a2e; padding: 48px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #8b5cf6; padding-bottom: 20px; margin-bottom: 32px; }
    .logo { font-size: 22px; font-weight: 900; color: #8b5cf6; letter-spacing: -0.03em; }
    .logo span { color: #06b6d4; }
    .meta { text-align: right; font-size: 12px; color: #666; }
    .meta strong { font-size: 14px; color: #1a1a2e; display: block; margin-bottom: 4px; }
    h1 { font-size: 24px; font-weight: 800; color: #1a1a2e; margin-bottom: 8px; }
    .subtitle { font-size: 13px; color: #666; margin-bottom: 32px; }
    .section { margin-bottom: 28px; }
    .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #8b5cf6; margin-bottom: 12px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
    .info-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
    .info-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px; }
    .info-card .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #9ca3af; margin-bottom: 4px; }
    .info-card .value { font-size: 15px; font-weight: 700; color: #1a1a2e; }
    .content-block { background: #f9fafb; border-left: 4px solid #8b5cf6; border-radius: 0 8px 8px 0; padding: 20px 24px; margin-top: 12px; }
    .content-block p { font-size: 13px; color: #374151; line-height: 1.75; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; display: flex; justify-content: space-between; font-size: 11px; color: #9ca3af; }
    .status-badge { display: inline-block; padding: 3px 10px; border-radius: 99px; font-size: 11px; font-weight: 700; background: #d1fae5; color: #065f46; }
    @media print { body { padding: 32px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">CEO <span>AI</span></div>
    <div class="meta">
      <strong>${report.name}</strong>
      Generated: ${new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'long', year:'numeric' })}
    </div>
  </div>

  <h1>${report.name}</h1>
  <p class="subtitle">Executive Intelligence Report — CEO AI Platform</p>

  <div class="section">
    <div class="section-title">Report Details</div>
    <div class="info-grid">
      <div class="info-card"><div class="label">Report Date</div><div class="value">${report.date}</div></div>
      <div class="info-card"><div class="label">File Size</div><div class="value">${report.size}</div></div>
      <div class="info-card"><div class="label">Status</div><div class="value"><span class="status-badge">${report.status}</span></div></div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Executive Summary</div>
    <div class="content-block">
      <p>This report was generated by the CEO AI multi-agent synthesis engine. It consolidates key operational signals, market intelligence data, and AI-driven recommendations relevant to <strong>${report.name}</strong>.</p>
      <br/>
      <p>All projections are based on real-time data streams ingested from connected B2B systems. Confidence interval: <strong>94.7%</strong>. Review and validate with your executive team before strategic deployment.</p>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Key Metrics</div>
    <div class="content-block">
      <p>• AI Signals Processed: <strong>48</strong> &nbsp;|&nbsp; Model Accuracy: <strong>99.4%</strong> &nbsp;|&nbsp; Anomalies Flagged: <strong>3</strong></p>
      <br/>
      <p>• Revenue Opportunity Detected: <strong>₹3.4L</strong> &nbsp;|&nbsp; Risk Score: <strong>2.1 / 10</strong> &nbsp;|&nbsp; Actions Pending: <strong>7</strong></p>
    </div>
  </div>

  <div class="footer">
    <span>CEO AI — Executive Intelligence Platform</span>
    <span>Confidential — For Executive Use Only</span>
    <span>Printed: ${new Date().toLocaleString('en-IN')}</span>
  </div>

  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`)
    win.document.close()
  }
}

export function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([])
  const [filter, setFilter] = useState<'all' | 'generated' | 'processing' | 'failed'>('all')
  const [isGenerating, setIsGenerating] = useState(false)
  const [newReportName, setNewReportName] = useState('')
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null)
  const [downloadingId, setDownloadingId] = useState<string | null>(null)
  const [errorMsg, setErrorMsg] = useState('')

  const fetchReports = async () => {
    try {
      const response = await api.get<Report[]>('/reports')
      if (response.data) {
        setReports(response.data)
      }
    } catch (err) {
      console.error('Failed to load reports', err)
    }
  }

  useEffect(() => {
    fetchReports()
  }, [])

  const handleGenerateReport = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!newReportName.trim()) return
    setIsGenerating(true)
    setErrorMsg('')
    try {
      const response = await api.post<Report>('/reports', {
        name: newReportName,
      })
      if (response.data) {
        setReports((prev) => [response.data!, ...prev])
        setNewReportName('')
      } else {
        setErrorMsg(response.error || 'Failed to generate report.')
      }
    } catch (err) {
      setErrorMsg('Network error generating report.')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleDelete = async (id: string) => {
    try {
      const response = await api.delete(`/reports/${id}`)
      if (response.status === 200 || !response.error) {
        setReports((prev) => prev.filter((r) => r.id !== id))
      }
    } catch (err) {
      console.error('Failed to delete report', err)
    } finally {
      setDeleteConfirmId(null)
    }
  }

  const handleDownload = (report: Report) => {
    setDownloadingId(report.id)
    setTimeout(() => {
      downloadReport(report)
      setDownloadingId(null)
    }, 800)
  }

  const filteredReports = reports.filter((r) => filter === 'all' || r.status === filter)

  return (
    <div className="reports animate-fade-in">
      {/* Delete Confirm Modal */}
      {deleteConfirmId && (
        <div className="delete-modal-overlay" onClick={() => setDeleteConfirmId(null)}>
          <div className="delete-modal glass animate-fade-in" onClick={e => e.stopPropagation()}>
            <div className="delete-modal-icon">🗑️</div>
            <h3>Delete Report?</h3>
            <p>This action cannot be undone. The report will be permanently removed from the archive.</p>
            <div className="delete-modal-actions">
              <button className="btn btn-ghost" onClick={() => setDeleteConfirmId(null)}>Cancel</button>
              <button className="btn btn-danger" onClick={() => handleDelete(deleteConfirmId)}>Delete</button>
            </div>
          </div>
        </div>
      )}

      {errorMsg && (
        <div style={{ background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.25)', padding: '0.75rem', borderRadius: '8px', color: '#f87171', fontSize: '0.85rem', marginBottom: '1rem', width: '100%' }}>
          ⚠️ {errorMsg}
        </div>
      )}

      {/* Filter Topbar */}
      <div className="reports-topbar">
        <div className="reports-filters">
          {(['all', 'generated', 'processing', 'failed'] as const).map((opt) => (
            <button
              key={opt}
              className={`filter-btn ${filter === opt ? 'active' : ''}`}
              onClick={() => setFilter(opt)}
            >
              {opt.toUpperCase()}
            </button>
          ))}
        </div>
        <div className="reports-count-badge">
          {filteredReports.length} {filteredReports.length === 1 ? 'report' : 'reports'}
        </div>
      </div>

      <div className="reports-layout">
        {/* Reports log list */}
        <div className="reports-log-card glass">
          <h3 className="panel-title">Document Archive</h3>
          <div className="reports-table-container">
            <table className="reports-table">
              <thead>
                <tr>
                  <th>Report Title</th>
                  <th>Date</th>
                  <th>Size</th>
                  <th>Type</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredReports.length === 0 && (
                  <tr>
                    <td colSpan={6} className="empty-table-row">No reports found.</td>
                  </tr>
                )}
                {filteredReports.map((report) => (
                  <tr key={report.id} className="report-row">
                    <td>
                      <div className="report-name-col">
                        <span className="report-icon-cube">▤</span>
                        <span className="report-name-text">{report.name}</span>
                      </div>
                    </td>
                    <td>{report.date}</td>
                    <td>{report.size}</td>
                    <td><span className="file-type-badge">{report.type}</span></td>
                    <td>
                      <span className={`badge badge-${
                        report.status === 'generated'
                          ? 'success'
                          : report.status === 'processing'
                          ? 'warning'
                          : 'danger'
                      }`}>
                        {report.status === 'processing' && <span className="processing-dot" />}
                        {report.status}
                      </span>
                    </td>
                    <td>
                      <div className="action-cell">
                        {report.status === 'generated' ? (
                          <button
                            className={`btn-download ${downloadingId === report.id ? 'downloading' : ''}`}
                            title="Download Report"
                            onClick={() => handleDownload(report)}
                            disabled={downloadingId === report.id}
                          >
                            {downloadingId === report.id ? (
                              <><span className="dl-spinner" /> Downloading...</>
                            ) : (
                              <>↓ Download</>
                            )}
                          </button>
                        ) : (
                          <span className="action-disabled">--</span>
                        )}
                        <button
                          className="btn-delete"
                          title="Delete Report"
                          onClick={() => setDeleteConfirmId(report.id)}
                        >
                          🗑
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Generate Report Form */}
        <div className="reports-generator glass">
          <h3 className="panel-title">Generate Custom Report</h3>
          <form className="generator-form" onSubmit={handleGenerateReport}>
            <div className="form-group">
              <label>Report Name</label>
              <input
                type="text"
                placeholder="e.g. Sales Competitor Audit Q3"
                value={newReportName}
                onChange={(e) => setNewReportName(e.target.value)}
                disabled={isGenerating}
                className="form-input"
              />
            </div>
            <div className="form-group">
              <label>Model Configuration Profile</label>
              <select className="form-select" disabled={isGenerating}>
                <option>Multi-Agent Synthesis (Deep Reasoning)</option>
                <option>Fast Heuristics & Operations Summary</option>
                <option>Supabase DB Schema Analyzer</option>
              </select>
            </div>
            <div className="form-group">
              <label>Data Window</label>
              <select className="form-select" disabled={isGenerating}>
                <option>Last 24 Hours</option>
                <option>Last 7 Days</option>
                <option>Last 30 Days</option>
              </select>
            </div>
            <button
              type="submit"
              className="btn btn-primary btn-submit-gen"
              disabled={isGenerating}
            >
              {isGenerating ? (
                <><span className="dl-spinner" /> Queuing Swarm...</>
              ) : (
                '✦ Generate Swarm Report'
              )}
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}

export default ReportsPage
